version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/python_service"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/sr_service"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
